### ISSUE TITLE
Errors when accepted and reloaded

### ISSUE THREAD

**Issue by rollecode** [digitoimistodude/air-cookie#1]
Causes console errors after cookies have been accepted and notification box is no longer there. Probably because there is no check for `    document.querySelector`.

1. Uncaught ReferenceError: manager is not defined
2. Uncaught TypeError: Cannot set properties of null (setting 'style')

Should be checked with `if (typeof xxx === 'undefined') {` or similar.

**Comment by timiwahalahti** [comment]
Fixed in [1.3.3](https://github.com/digitoimistodude/air-cookie/releases/tag/1.1.3).
